### ISSUE TITLE
Lebenslauf: bei Ausbildungen, Erfahrung und Kenntnisse ist die Eingabe nicht übersichtlich

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#100]
Geht es so wie im Reiter "über mich" es nebeneinander zu schreiben statt untereinander? Bzw. auch bei Bewerbung - also bei allen Editing Fenstern?

**Comment by leoluttenberger** [comment]
Ja ich werde die Editing Fenster anpassen und dann sehen wir mal ob das Design so besser passt.
