### ISSUE TITLE
Auswahl Ausbildungen

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#115]
**Prio: Niedrig**

Lebenslauf -> Ausbildungen - Neu anlegen

Bei der Auswahl der Ausbildung fehlen noch Fachschulen und Uni bzw. vl generell ein offenes Feld, falls wir was übersehen haben?
In jedem Fall Option "Fachschule", "Fachhochschule" und "Universität" im Dropdown hinzufügen.
Dann müsste ggf. statt nur Schwerpunkt auch stehen: "Schwerpunkt/Fach"

**Comment by leoluttenberger** [comment]
Kannst du mir bitte eine vollständige Liste posten, damit ich das Dropdown füllen kann. Danke!

**Comment by b-goebl** [comment]
s. Rocketchat :-)
