### ISSUE TITLE
Bewerbungsansicht - Motivationsschreiben rutscht über 2 Zeilen

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#118]
Bewerbung --> Anzeige Bewerbung

Bei der Formattierung der Anzeige "Motivationsschreiben angehängt" bricht es etwas unschön um (s. Screenshot).
![Screenshot_20230129-114309](https://user-images.githubusercontent.com/35298425/215321322-74a751a2-1006-4c47-8ff7-9b7fdace4747.png)

**Comment by leoluttenberger** [comment]
fixed in commit 8138af1999de3a09fca953100e24d5ee64edbbf0
