### ISSUE TITLE
Über mich - bei Namen und Geburtsort springt der Text beim Schreiben  

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#120]
Über mich - Vorname, Nachname, Geburtsort

Wenn ich versuche was einzugeben, springt der Text vor/zurück während ich tippe - die Ansicht ist beim fertigen Text aber OK, daher vermutlich keine hohe Prio

**Comment by leoluttenberger** [comment]
Kannst du ein Screenshot oder video hochladen, sodass ich genau weiß wie der Bug aussieht? Danke!
