### ISSUE TITLE
Kenntnisse - zwischen Sprache und Platzhalter kein Abstand

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#121]
Kleinigkeit - keine hohe Prio

Sprachkenntnisse -> Sprache: kein Leerzeichen zwischen "Sprache" und der Eingabe bzw. dem Platzhalter

**Comment by leoluttenberger** [comment]
Fixed commit f3f469ce18fd8961b5b588cdc3d1f4f3a4e7ec37
