### ISSUE TITLE
Bewerbungen - Archiv - x Zeichen zu groß

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#122]
Bewerbungen -> Archiv 

Da ist der x Zeichen sehr groß geraten (ich vermute es ist das Zeichen für Motivationsschreiben fehlt?)

![WhatsApp Image 2023-01-30 at 14 44 02](https://user-images.githubusercontent.com/122562604/215494016-aade2cd4-c4e3-4dde-a070-7cba2e7c8420.jpeg)

**Comment by leoluttenberger** [comment]
Fixed in commit f3f469ce18fd8961b5b588cdc3d1f4f3a4e7ec37
