### ISSUE TITLE
Rechtschreibung

### ISSUE THREAD

**Issue by ViktoriaPaar** [leoluttenberger/wedesign#142]
**Describe the bug**
Bewerbung ->  Bewerbungsansicht -> Speichern & Senden - > In meinem persönlichen Emailprogramm steht dann:
"Die Dateien findest im Ordner Dokumente"  -> hier fehlt das Du.

**Smartphone (please complete the following information):**
 - Device: Samsung 22Plus
 - Browser google
 
**Additional context**
![b8dcd2ae-992e-4636-8bc1-64cab51ef5b4](https://user-images.githubusercontent.com/129181444/228237815-5145151b-28f9-4bda-ba9a-7590448abac7.jpg)

**Comment by leoluttenberger** [comment]
Dafür muss ein Productions Sever im hingrund laufen den ich noch nicht live geschalten habe. Ist aber schon implementiert.
