### ISSUE TITLE
Bewerbungsansicht - Export funktioniert nicht

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#146]
Wenn ich bei einer (sowohl alten als auch neuen) Bewerbung auf Bewerbungsansicht (das Wort würde ich btw. zusammen schreiben) gehe, wird mir kein Preview gezeigt 
![WhatsApp Image 2023-04-03 at 20 38 22](https://user-images.githubusercontent.com/122562604/229597785-353d8532-acc4-4196-b919-39cf801c5342.jpeg)

**Comment by leoluttenberger** [comment]
fixed in commit  503102ed20ade28c1ec2820e1cc8d418698e62ab
