### ISSUE TITLE
Bewerbung - eine bestehende Bewerbung kann nicht nachträglich verändert werden

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#147]
Wenn ich eine Bewerbung anklicke, verändere etwas in der Hauptansicht und klicke oben auf speichern - schließt das Fenster, aber es speichert nicht - wenn ich wieder reingehe, sind die Änderungen weg bzw. werden auch nicht in der Übersicht gezeigt

**Comment by leoluttenberger** [comment]
fixed bug in commit 450ac172df29c697a43811abe31fda749a623273
