### ISSUE TITLE
Kalender ist bei mir wieder verschwunden :D 

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#148]
Oops, Kalender wieder ganz weg....auch nach dem Schließen nicht wieder da... 
![WhatsApp Image 2023-04-03 at 20 56 46](https://user-images.githubusercontent.com/122562604/229601366-df11696f-204b-44be-b352-af8edfdde673.jpeg)

**Comment by leoluttenberger** [comment]
Kannst du mir die Steps in den Kommentar schreiben, wie dre Fehler zustande gekommen ist,  damit ich den Fehler reproduzieren kann. Danke.
