### ISSUE TITLE
Warnhinweise bei Anlegen von Bewerbung

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#149]
**Describe the bug**
Es wird ein Warnhinweis beim Anlegen einer neuen Bewerbung angezeigt, der eigentlich bei den eingegeben Daten nicht aufschienen sollte ("darf nur Buchstaben und Zahlen" <-- da fehlt auch das "enthalten"). Problem evt. Umlaut? Leerzeichen?

**To Reproduce**
Bewerbung --> ( + )
Hätte den Namen der Firma mit „Bäckerei X“ angelegt. Warnhinweis: darf nur Buchstaben und Zahlen.

**Expected behavior**
Möglichkeit zum Speichern der Bewerbung sollte weiterhin aktiv sein

**Smartphone (please complete the following information):**
Android 13, Pixel 4a, Native App

Testversion vom 4.4.23

**Comment by leoluttenberger** [comment]
Fixed with commit 10e542145219867dad23bcb4a9f4bbee74d0d05d
