### ISSUE TITLE
Bewerbungen ohne Startdum scheinen nicht im Kalender auf

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#150]
**Describe the bug**
Bewerbungen, die ohne Startdatum angelegt werden, scheinen zwar in der Übersicht unter dem Kalender in "Erinnerungen" auf, aber nicht im Kalender. Mit zwei Bewerbungen versucht.

**To Reproduce**
Unter "Bewerbungen" --> ( + ) neue Bewerbung ohne Info zum Startdatum anlegen
Dann im Kalender gegenchecken

**Expected behavior**
Anzeige der Bewerbung sowohl in der Übersicht unter dem Kalender, als auch im Kalender selber als Punkt bzw. mit Kreismarkierungen zu Beginn und Ende.

**Smartphone (please complete the following information):**
Android 13, Pixel 4a, Native App

Testversion vom 4.4.23
![Screenshot_20230404-135635](https://user-images.githubusercontent.com/35298425/229784935-f86b5686-76fe-4abc-87b3-ef05b9abca33.png)

**Comment by leoluttenberger** [comment]
Already fixed in commit 56920c92821911f5c982a01412e53136d10cbaf5
