### ISSUE TITLE
Keine Änderung von Startdatum via Kalenderübersicht möglich + extra Punkte

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#151]
**Describe the bug**
Bei mehrmaligen Versuchen über die Seite "Erinnerungen" via Klick das Startdatum der Bewerbung "Äpptester 1A!" zu ändern folgende Probleme:
- Startdatum wurde auch nach Speichern ("Termin Speichern" nicht übernommen)
- Es wurden dabei mehrere Punkte im Kalender angelegt (diese waren aber nur tempärer, nach Anlegen einer neuen Bewerbung über Bewerbung --> (+) wieder weg)
(die im Screenshot im ersten Bild dargestellten Punkte sind bereits nach davor versuchten Änderungen des Startdatum entstanden.)
![Bug_Erinnerungen_Startdaum](https://user-images.githubusercontent.com/35298425/229786537-1a69e0ca-6d22-49ba-9db3-a5f55e2c9290.PNG)

**To Reproduce**
Bewerbung regulär ohne Startdatum über Bewerbungen --> (+) angelegt
In "Erinnerungen" das Kärtchen der Bewerbung anklicken
Startdum einstellen und speichern

**Expected behavior**
Startdatum scheint bei der Bewerbung fix gespeichert auf

**Smartphone (please complete the following information):**
Android 13, Pixel 4a, Native App

Testversion vom 4.4.23

**Comment by leoluttenberger** [comment]
Bewerbungsfenster/Deadline ist etwas anderes als Bewerbungsgespräch. So sollte der Type nicht änderbar sein im Formular was ich noch ändern werde. Das hat wahrscheinlich die Verwirrung ausgelöst :)
