### ISSUE TITLE
Neue Bewerbungen scheinen auch im Archiv auf

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#153]
Bei mir erscheinen neue Bewerbungen auch gleich im Archiv auf (event. mit meinem sonstigen Cache Problem zu tun?)

**Comment by leoluttenberger** [comment]
Nein ich hab zu Zeit keine eigenes Archiv angelegt und zeige die aktuellen Bewerbungen an. Muss ich noch implementieren.
