### ISSUE TITLE
Lebenslauf - Kenntnisse - Default Anzeige hat zwei leere Felder

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#159]
Lebenslauf - Kenntnisse - default: es sind zwei Felder zu sehen und das X. Können die leeren Felder weg? 
![WhatsApp Image 2023-04-05 at 19 17 28](https://user-images.githubusercontent.com/122562604/230156002-a620c67e-30c0-43a5-a8f6-b59124070e2b.jpeg)

**Comment by leoluttenberger** [comment]
Ich kann das Formular so gestalten das eine Auswahl getroffen werden muss und die Felder nicht leer sein dürfen. Doch wenn Felder erstellt werden mit, keinen Daten müssen, diese auch angezeigt werden.
