### ISSUE TITLE
Neue Bewerbung anlegen - Firma - Label Fehlermeldung "Firma darf nur Buchstaben und Zahlen haben" bleibt nach Beheben

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#160]
Bewerbung - neue Bewerbung anlegen - Fima eingeben - Leerzeichen eingeben nach dem ersten Wort (um das zweite Wort des Firmennamens zu schreiben) -> das Fehler-Label ("Firma darf nur Buchstaben und Zahlen haben") bleibt weiterhin sichtbar 

Übrigens, beim Fehler-Label fehlt "haben" - derzeit "Firma darf nur Buchstaben und Zahlen"

Begründung: Als User weiß ich nicht ob das Problem noch besteht und probiere im Zweifel so lange, bis es weg ist
![WhatsApp Image 2023-04-05 at 19 31 54](https://user-images.githubusercontent.com/122562604/230158559-dcfc4081-1c66-4d7b-8cc1-557416892ef7.jpeg)

**Comment by leoluttenberger** [comment]
fixed bug in commit 24a48f560a3926754984f26ebec5e278c57a3ddc
