### ISSUE TITLE
Beitrag und Kompetenz vertauscht

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#170]
Bewerbung --> Motivationsschreiben bearbeiten

Die Bezeichnungen Beitrag und Kompetenz sind in der Übersicht und in der Bearbeitungsansicht vertauscht.
Wenn ich auf das rot markierte Editing-Symbol bei Kompetenzen klicke, steht in der Bearbeitungsansicht "Beitrag" (und umgekehrt).
![image](https://user-images.githubusercontent.com/35298425/232587779-74e5b2dd-3cac-4153-8987-ea687d427011.png)

**Comment by leoluttenberger** [comment]
Danke! wird ausgebessert.
