### ISSUE TITLE
Motivationsschreiben Vorlagen - Texte, die zu ändern sind, in eckige Klammern setzen

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#204]
Als Userin kann ich möglicherweise übersehen, wenn etwas noch (Gender, Beruf, etc) geändert werden muss. Könnten wir hier die eckigen Klammer (ich glaube wir hatten uns auf eckige Klammern geeinigt) noch haben?

**Comment by leoluttenberger** [comment]
erledigt in commit 75dce1887b13d8370aaada3de232cd4b4420304d
