### ISSUE TITLE
Test Case - Profil Bild laden

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#206]
**Test Case**
Profil Bild laden

**Description**
Kontrolle ob ein Profilbild geladen werden kann.

**Test steps**
1. Gehe zu Lebenslauf
2. Klicke auf Profilbild ändern
3. Klicke direkt aufs Bild
4. Wähle ein Bild aus
5. Schneide das Bild zu
6. Schließe das Fenster und speicher das Bild ab
7. Wiederhole diesen Ablauf von  Step 1-5 nochmals.

**Expected result**
Bild soll als Profilbild geladen werden und auch beim zweiten Durchgang das Bild geändert werden.

**Actual result**
Es funktioniert wie gewollt. Ich habe aber einen Bug gefunden und eine Anmerkung, welche beide gleich als Kommentar zu sehen sein werden.

**Status**
- [ ] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bug**
Man kann beim Croppen an das Bild heranzoomen. Dies geht auf allen Geräten (am Computer mit Mausrad und auf Handys mit zwei Fingern). Wenn man dies macht, ist die Umrandung des Bildes kaputt.

![grafik](https://github.com/leoluttenberger/wedesign/assets/134038564/87093739-61a2-462a-8fac-b293bfbaf0e2)


**Anmerkung**
1: Wenn man das Profilbild ändern möchte drückt man darauf, allerdings wenn man unabsichtlich darauf gedrückt hat, geht die Taste für das Editieren erst weg wenn man vom Lebenslauf zu einem anderen Tab, wie dem Home, wechselt. Ich habe zuerst versucht auf eine leere Stelle zu drücken, damit das Symbol zum Editieren weggeht.

2: Wenn man das Cropping ändern möchte beim selben Bild, muss man zuerst ein anderes Bild auswählen damit man es erneut anders Croppen kann.

3: Wenn man auf den Handys das Bild ändern möchte, wird ein Fenster geöffnet bei dem nicht gleich, falls gewollt, auf die Kamera zugreifen kann bzw. falls diese Funktion vorhanden ist, habe ich diese nicht gefunden.

**Comment by leoluttenberger** [comment]
Punkt 3 Camera input ist nicht implementiert.

**Comment by leoluttenberger** [comment]
Fixed Punkt 1+2. Ich habe einen Profilbild Edit button hinzugefügt und auch das wiederholte Cropping des Profilbildes ist jetzt möglich. Commit cef4caea02d8acaba69d0337e0ad0beef5f1f678

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.
