### ISSUE TITLE
Test case - Über mich eingabe

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#207]
**Test Case**
Über mich eingabe

**Description**
Kontrolliere ob alle Daten in Über mich korrekt eingegeben werden können.

**Test steps**

1. In Lebenslauf und Über mich
2. Click auf den Stift "Bearbeitung Button"
3. Fülle deine Daten in das Pop up ein.
5. Drücke recht oben auf speichern.
6. Kontrolliere ob Daten richtig eingeben würden.

**Expected result**
Alle Daten werden richtig eingegeben und angezeigt.

**Actual result**
 <Hier bitte ausfüllen>

**Status**
- [x] Pass
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Anmerkung**
Platzhalter-Text ist immer sichtbar, auch wenn man gerade nicht die Daten editiert. Außerdem, wenn man beispielsweise keine Titel hat, wird einem immer der Platzhalter-Text für den Doktortitel angezeigt.

**Comment by leoluttenberger** [comment]
Ok also bei der Lebenslaufübersicht sollte kein Platzhalter-Text stehen. Wird ausgebessert!

**Comment by leoluttenberger** [comment]
Platzhalter-Text wurde aus der Lebenslauf Übersicht entfernt in Commit 1171843396cfe40972ffcdbb411ec11226cdc9c7

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.
