### ISSUE TITLE
Test case - Ausbildungen eingabe

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#208]
**Test Case**
Ausbildungen eingabe

**Description**
Kontrolliere ob Erstellung und Bearbeitung von Ausbildungen ist möglich und dir Formulare sind korrekt.

**Test steps**
1. In Lebenslauf und Ausbildungen
2. Click auf + Button 
3. Fülle deine Daten ein
4. Einmal mit laufen
5. Wiederhole den Vorgang ohne laufend und einmal mit Anmerkung.
6. Schließe das Pop-up und kontrolliere Liste in Tab Ausbildungen.  
7. Drücke jede der List Buttons
8. Editiere das Formular und kontrolliere ob Daten richtig sind.

**Expected result**
Es sollten drei Eintragungen als liste in Ausbildungen mit den richtigen Daten eingetragen sein.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bug**
1: Man kann bei Ausbildungen nicht ein Jahr vor 2020 eingeben.

2: In der Liste der Ausbildungen zeigt es bei der Datumsangabe immer den 4. vom Monat und danach eine Reihe von Ziffern an.

3: Wenn man versucht eine Ausbildung an die unterste Stelle zu verschieben, geht das bei den Android-Handys nicht.

4: Die Funktion zum Verschieben geht hier bei der Webversion nicht.

**Comment by leoluttenberger** [comment]
Punkt 3+4 in BUG Ticket #235

**Comment by leoluttenberger** [comment]
Für Punkt 1+2 war das Styling für den Datepicker nicht korrekt und so wurden die Jahre und Monate nicht richtig angezeigt. Wurde im Commit 85999919dd9ccf5c6262fbf148af46430d0a6724 ausgebessert.

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.

**Comment by Marius-Marincek** [comment]
**Bugs**
1. Auf Smartphone und Tablet werden die Anmerkungen in der normalen Ansicht nicht gezeigt.

2. Auf Smartphone und Tablet ist der Bug mit dem nach unten verschieben noch da.
