### ISSUE TITLE
Test case - Erfahrugen eingabe

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#210]
**Test Case**
Erfahrugen  eingabe

**Description**
Kontrolliere ob Erstellung und Bearbeitung von Erfahrugen ist möglich und dir Formulare sind korrekt.

**Test steps**
1. In Lebenslauf und Erfahrugen
2. Click auf + Button 
3. Fülle deine Daten ein
4. Wiederhole den Vorgang 3 mal.
5. Schließe das Pop-up und kontrolliere Liste in Tab Erfahrugen .  
6. Drücke jede der List Buttons
7. Editiere das Formular und kontrolliere ob Daten richtig sind.

**Expected result**
Es sollten drei Eintragungen als liste in Erfahrugen  mit den richtigen Daten eingetragen sein.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bug**
1: Wenn man versucht eine Erfahrung an die unterste Stelle zu verschieben, geht das bei den Android-Handys nicht.

2: Die Funktion zum Verschieben geht hier bei der Webversion nicht.


**Anmerkungen**
Beim Editieren einer Erfahrung steht unten immer noch Hinzufügen. Dies könnte verwirrend sein, da es in dem Fall nur zum Editieren ist.

**Comment by leoluttenberger** [comment]
Ist jetzt zusammengefasst in BUG Ticket #235

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.

**Comment by Marius-Marincek** [comment]
**Bugs**
1. Bei meinem Computer in der Webversion, nur in Firefox, kann ich bei keinem Tab außer Kenntnisse etwas hinzufügen, da die Plus-Symbole nicht angezeigt werden. Außerdem ist das Plus-Symbol von den Kenntnissen beim Lebenslauf statt bei den Kenntnissen. In anderen Browsern und auf anderen Computern funktioniert das Hinzufügen usw. einwandfrei.

2. In der Browserversion kann man die Erfahrungen nicht in der Reihenfolge verschieben bzw. ist da der Bug noch da.

3. Auf dem Tablet kann man die Erfahrungen nicht nach untern verschieben bzw. ist da der Bug noch da.

4. Auf dem Tablet ist der Spielraum, bei dem man eine Erfahrung in die Mitte (oder dem über dem Untersten) schieben kann nur zirka ein Milimeter zwischen dem oberen und dem unteren.
