### ISSUE TITLE
Test Case - Kenntnisse eingabe

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#211]
**Test Case**
 Kenntnisse eingabe

**Description**
Kontrolliere ob Erstellung und Bearbeitung von Kenntnisse ist möglich und dir Formulare sind korrekt.

**Test steps**
1. In Lebenslauf und Kenntnisse
2. Drücke auf + Button 
3. Fülle deine Daten ein
4. Wiederhole den Vorgang 3 mal.
5. Schließe das Pop-up und kontrolliere Liste in Tab Kenntnisse .  
6. Drücke jede der List Buttons
7. Editiere das Formular und kontrolliere ob Daten richtig sind.

**Expected result**
Es sollten drei Eintragungen als liste in Kenntnisse  mit den richtigen Daten eingetragen sein.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bug**
1: Wenn man versucht ein Kenntniss an die unterste Stelle zu verschieben, geht das bei den Android-Handys nicht.

2: Die Funktion zum Verschieben geht hier bei der Webversion nicht.

3: Beim Hinzufügen steht Erfahrung hinzufügen, obwohl ein Kenntniss hinzugefügt wird.


**Anmerkungen**
Beim Editieren eines Kenntnisses steht unten immer noch Hinzufügen.

**Comment by leoluttenberger** [comment]
1+2 in BUG Ticket #235

**Comment by leoluttenberger** [comment]
Fixed Punkt 3 in Commit 0c3efbd1eafdf53c3c7ca85c258e4f47ef584eba

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.

**Comment by Marius-Marincek** [comment]
**Bugs**
Auf Smartphone und Tablet ist der Bug mit dem nach unten verschieben noch da.
