### ISSUE TITLE
Test Case - Kontrolliere Button Liste Drag and Drop

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#212]
**Test Case**
Kontrolliere Button Liste Drag and Drop

**Description**
Erstelle in Lebenslauf und Ausbildungen mehere Eingaben um eine Butto Liste zu bekommen. Oben recht gibt es den Toggle Button für Drag und Drop um die Elemente zu verschieben. 

**Test steps**

1. Go to Lebenslauf und Ausbildungen
2. Füge mehere Eingabe Elemente hinzu
3. Clicke oben rechts auf das Drag and drop Toggle Icon
4. Versuche die Elemente aus der Liste zu verschieben.

**Expected result**
Elemente in der Liste sollten verschiebar sein.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [ ] Android app smarthphone
- [ ] Android app tabled
- [ ] Web

**Status**
- [ ] Passt
- [ ] Fail

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.

**Comment by Marius-Marincek** [comment]
**Bugs**
1. Lässt sich in Browserversion nicht verschieben.

2. Man kann auf Smartphone und Tablet es nicht an die unterste Stelle verschieben.

3. Auf dem Tablet ist der Spielraum, bei dem man eine Erfahrung in die Mitte (oder dem über dem Untersten) schieben kann nur zirka ein Milimeter zwischen dem oberen und dem unteren.
