### ISSUE TITLE
Test case - Lebenslauf Ansicht

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#213]
**Test Case**
Lebenslauf Ansicht

**Description**
Kontrolliere ob alle Daten korrekt in die Lebenslauf Ansicht übernommen werden.

**Test steps**

1. Gehe zu Lebenslauf -> über mich
2. Drücke auf Lebenslauf Ansicht
3. Sehe dir die PDF Ansicht vom Lebenslauf an

**Expected result**
Es sollten alle Daten aus dem Lebenslauf Elementen in die Lebenslauf PDF Ansicht übernommen werden.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Pass
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Anmerkungen**
Beim Download des PDFs bei der Webversion erhält man ein .docx und ein PDF.
Ich vermute, dass dies so sein soll.

**Comment by leoluttenberger** [comment]
Ja genau in der Webversion downloaded man ein .docx und ein PDF.

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.
