### ISSUE TITLE
Test Case - Erstellung Bewerbung

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#215]
**Test Case #8**
Erstellung Bewerbung

**Description**
Erstellung und Bearbeitung einer Bewerbung

**Test steps**

1. Gehe zu Bewerbung
2. Drücke auf + Icon und erstelle eine neue Bewerbung
3. Speichere und schließe das Pop-Up
4. Drücke auf das Element in der Liste um zu bearbeiten
5. Füge weitere Daten zur neuen Bewerbung wie Adresse zB.
6. Speichere und schließe die Bewerbung.

**Expected result**
Beim erstellen der Bewerbung sollte das Ende verpflichtent sein und alle Daten sollten richtig in die Elementen Liste übernommen werden.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bugs**
Beim Erstellen einer Bewerbung auf Android-Geräten zählt nicht nur ein Klick auf das X-Symbol zum Abbrechen, sondern daneben auch die leere Fläche und daneben der Text mit Bewerbung.

**Comment by leoluttenberger** [comment]
Dass ist das richtige Verhalten. Doch werde ich mir das als Feedback notieren, dass man das Verhalten noch überarbeiten kann/soll.
