### ISSUE TITLE
Test Case - Erstellung Motivationsschreiben

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#216]
**Test Case**
Erstellung Motivationsschreiben

**Description**
Erstellen und bearbeiten vom Motivationschreiben.

**Test steps**

1. Gehe zu Bewerbung -> Drücke auf Bewerbunge in der Elementen Liste
2. Bearbeite Bewerbungs Formular
3. Drücke auf Motivationschreiben bearbeiten. 
4. Drücke auf einen Editier-Button und wähle eine Vorlage aus.
5. Kontrolliere ob die Vorlage übernommen wird.
6. Drücke nacheinnander auf alle Editier-Button und fülle alle Bereiche aus.
7. Kontrolliere ob alles übernommen ist.

**Expected result**
Vorlagen sollen angezeigt werden und alle Eingaben sollen in das Formular übernommen werden.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bugs**
Wenn man mit dem Motivationsschreiben fertig ist und wieder im Fenster der Bewerbung ist, dann steht unten noch fehlt. Erst wenn man aus dem Fenster heraus geht und wieder reingeht ist das nicht mehr so.

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.
