### ISSUE TITLE
Test Case - Kalender Eingabe und Bearbeitung

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#218]
**Test Case*
Kalender Eingabe und Bearbeitung

**Description**
Erstelle Termine mit verschiedenen Labels und bearbeite diese.

**Test steps**

1. Gehe zu Erinnerungen
2. Drücke auf + Icon
3. Erstelle ingesamt 4 Termine mit veschiedenen Labels
4. Speichere und schieße das  Fenster
5. Kontrolliere ob alle Termine eingetragen sind
6. Drücke auf einen Termin im Kalender
7. Kontrolliere ob die Auswahl stimmt

**Expected result**
Alle vier farben der erstellten Termine mit den verschiedene Labels sollen angezeigt werden. Die Daten der Termine sollten korrekt angezeit werden und bei der Auswahl im Kalender sollte nur der Termin angezeigt werden der auf dem gleichen augewählten Tag fällt.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bugs**
1: Wenn man einen Termin erstellt und man das Erstellfenster schließt, werden Termine von einem anderen Monat angezeigt.

2: Wenn man auf ein Datum drückt und dann Alle Termine im Monat drückt, und dann wieder auf den selben Tag geht, dann werden immer noch alle Termine angezeigt, obwohl der Text sagt, dass es nur Termine von dem Tag sein sollen.

**Comment by leoluttenberger** [comment]
Bitte teste diesen Test Case nochmals durch.
