### ISSUE TITLE
Test Case - Tipps und Tricks

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#250]
**Test Case**
Tipps und Tricks kontrolle 

**Description**
Kontrolliere ob Tipps und Tricks richtig angezeigt werden 

**Test steps**

1. Go to Home
2. Klicke auf Tipps und Tricks
3. Swipe durch die drei Menüpunkte
4. Öffne die Akkordions in Menupunk Links
5. Kontrolliere ob alle Links korrekt anklickbar sind

**Expected result**
Tipp und Tricks sollen sich öffnen und alle Links im Menupunkt Links sollen richtig sein.

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bugs**
Beim Menüpunkt Stellensuche kann man nur weiter swipen, wenn man bei einem der Reiter oben swiped. Bei den anderen Menüpunkten geht es überall.

**Anmerkungen**
Die Animation beim aufmachen eines Reiters ist beim Schließen zu langsam. Ich habe zuerst ein weiteres Mal gedrückt, weil ich kurz gedacht habe, dass es nicht auf meinen Input reagiert hat.
