### ISSUE TITLE
Test Case - Deep Links zu Kalender und Bewerbungen

### ISSUE THREAD

**Issue by leoluttenberger** [leoluttenberger/wedesign#252]
**Test Case**
Deep Links zu Kalender und Bewerbungen

**Description**
Kontrolliere ob die Deep Links zu Kalender und Bewerbungen funktionieren.

**Test steps**

1. Erstelle eine Bewerbung falls sich vorhanden
2. Gehe zu Home
3. Klicke auf einen Tab in Aktuelle Bewerbungen
4. Kontrolliere ob die Daten korrekt sind und ob du weitergeleitet würdest
5. Gehe zu Home
6. Klicke auf einen Tab in Erinnerungen
7. Kontrolliere ob die Daten korrekt sind und ob du weitergeleitet würdest

**Expected result**
Deep Links sollten dich zum richtigen Menüpunkt füren und die Daten sollten korrekt sein

**Actual result**
 <Hier bitte ausfüllen>

**Device**
- [x] Android app Smarthphone
- [x] Android app Tablet
- [x] Web

**Status**
- [x] Passt
- [ ] Fail

**Comment by Marius-Marincek** [comment]
**Bugs**
Wenn der Termin im selben Monat ist wie das derzeitige Datum, zeigt es bei den Erinnerungen bei Nächste Termine den Termin nicht an.

**Comment by leoluttenberger** [comment]
corrected in commit e85cf7cd4661200f32067fb1b2caf20d42dee3bd
