### ISSUE TITLE
Kein Download bei "Vorschau & Teilen" von CV und Motivationsschreiben

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#279]
**Describe the bug**
sowohl bei CV als auch bei Motivationsschreiben löst der "Vorschau & Teilen"-Button bei mir keinen Download mehr aus.

**To Reproduce**
Menüpunkt "CV" -> Button "Vorschau & Teilen", alternativ:
Menüpunkt "Bewerbung" --> Bewerbung auswählen --> Vorschau & Teilen

**Expected behavior**
Sowohl die Anzeige zum Teilen erscheint (die sehe ich auch), als auch ein automatischer Download in den Hndy-Speicher wird veranlasst. Der Download passiert aktuell nicht.

**Smartphone (please complete the following information): **
- Device: Pixel 4a
- OS: Android 13

**Comment by leoluttenberger** [comment]
Ich habe die Rechte in der Version 0.8.0 für Android nicht richtig vergeben. Sollte in Release 0.9.0 gefixed sein. Sehe ich mir aber nochmals an.
