### ISSUE TITLE
"laufend" verruscht nach unten

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#303]
Lebenslauf -> Ausbildungen -> "laufend" verrutscht nach unten. Und, könnte "laufend" eine geteilte Zeile mit Ende haben? Weil sonst nicht sichtbar/klar worauf es sich bezieht 

![WhatsApp Image 2023-08-08 at 13 28 36(1)](https://github.com/leoluttenberger/wedesign/assets/122562604/bcf8d51c-08fb-4e6e-8dec-904e5f12db20)

**Comment by b-goebl** [comment]
Start + Ende in einer Zeile.
Laufend in eigener Zeile darunter, wenn man laufend anklickt verschwindet Ende

**Comment by vienasus** [comment]
Das ist bei mir immer noch gleich?

**Comment by vienasus** [comment]
Nachtrag: wenn ich eine neue Ausbildung anlege, ist das laufend oben, wie im Screenshot oben; wenn ich eine alte bearbeite, ist es unten bei den Anmerkungen und verrutscht nicht 
![WhatsApp Image 2023-08-16 at 16 00 21](https://github.com/leoluttenberger/wedesign/assets/122562604/20de333c-2746-491f-914e-cc30dd06b478)
