### ISSUE TITLE
Tipps & Tricks - FAQ - veraltete Infos zum Archiv

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#305]
Home Screen -> Tipps & Tricks -> "FAQ" -> veraltete Infos zum Archiv

Frage: "Wie viele Bewerbungen kann ich gleichzeitig speichern"
Bitte in der Antwort den Satz löschen: "Diese werden im "Archiv" angezeigt"

Frage: "Was ist der Unterschied zwischen Offen und Archiv"
Bitte ganz löschen (Frage und Antwort)

Frage: "Wo finde ich eine Übersicht aller gespeicherten Bewerbungen?"
Antwort bitte anpassen: 
"Im Menüpunkt 'Bewerbungen' findest du eine Übersicht aller von dir angelegten Bewerbungen. Wenn du diese löscht (=entfernst), kannst du leider nicht mehr wiederherstellen."

**Comment by vienasus** [comment]
Der alte Text zum Archiv ist bei mir immer noch da

**Comment by leoluttenberger** [comment]
Wird in ticket #344 behoben.

**Comment by vienasus** [comment]
Diese Frage von oben ist bei mir noch falsch drin:

Frage: "Wo finde ich eine Übersicht aller gespeicherten Bewerbungen?"
Antwort bitte anpassen:
"Im Menüpunkt 'Bewerbungen' findest du eine Übersicht aller von dir angelegten Bewerbungen. Wenn du diese löscht (=entfernst), kannst du leider nicht mehr wiederherstellen."
