### ISSUE TITLE
FAQ - Link geht nicht 

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#306]
Home Screen -> Tipps&Tricks -> "FAQ"-> Frage: Muss ich in allen Feldern (Betreff...) Text hinzufügen -> in der Antwort ("Bewerbungsportal-Musterbewerbungen (ams.or.at)") wurde der Link nicht mitkopiert bzw. kann nicht angeklickt werden. Da ist der Link: https://bewerbungsportal.ams.or.at/bewerbungsportal/#!/musterbewerbungen

**Comment by leoluttenberger** [comment]
in der faq i have to change the component to support links. Links should be in the tap links
