### ISSUE TITLE
Texteditor Motivationsschreiben - Textvorlagen

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#310]
Wenn ich ein Motivationsschreiben neu anlege und bearbeite und mittels Klick auf den Stift neben dem Feld den Editor öffne:
aktuell steht zuerst bei "aktueller Text": "Neuer Text"
Beim ersten Wischen nach recht steht "leer"
**Hier soll statt "leer" stehen: "Schreibe hier deinen Text. Weitere Vorlagen findest du, wenn du nach rechts wischt."**

**Comment by vienasus** [comment]
Hier ist bei mir "Schreibe hier deinen Text. Weitere Vorlagen findest du, wenn du nach rechts wischt." auch noch nicht drin
