### ISSUE TITLE
Pfeile in Dropdown-Feldern doppelt

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#313]
**Describe the bug**
Bei Dropdown Menüs im CV/Motivationsschreiben werden zwei Pfeile nach unten angezeigt

**Comment by vienasus** [comment]
![WhatsApp Image 2023-08-08 at 15 06 24(1)](https://github.com/leoluttenberger/wedesign/assets/122562604/45f1a918-1ff9-4fb8-849a-e2ae5d3c12b8)

**Comment by vienasus** [comment]
Im Lebenslauf wird es bei mir in der Übersicht (bevor ich auf den Stift zum Bearbeiten klicke) immer ncoh gleich angezeigt
