### ISSUE TITLE
Lebenslauf - DOCX Export fehlt

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#353]
Lebenslauf -> Vorschau und Teilen -> Teilen Icon 
Es wird bei mir jetzt nur das PDF, und kein DOCX exportiert.

**Comment by leoluttenberger** [comment]
Kannst du mir einen Screenshot vom sharing screen zeigen? Wir die Datei nicht abgespeichert oder auch nicht geshared?

**Comment by vienasus** [comment]
Jetzt geht es, danke!
