### ISSUE TITLE
Rechtschreibprüfung - es erscheint nur "no message" 

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#360]
Bewerbung -> Motivationsschreiben bearbeiten -> Editierfenster anklicken -> die Rechtschreibprüfung unterstreicht nur die fehler, zeigt aber keine alternativen an, sondern nur "no message". Ist das so beabsichtigt? 

![WhatsApp Image 2023-08-24 at 15 23 04](https://github.com/leoluttenberger/wedesign/assets/122562604/54aed863-c00c-4864-b3b0-e3d0b525c702)

**Comment by leoluttenberger** [comment]
Klick kurz neben den Text und es sollte dann die Rechtschreibpruefung kommen.

**Comment by leoluttenberger** [comment]
Ich habe eine Anleitung hinzugefügt das man nochmals auf neben dem Feld drücken soll um die Rechschreibprüfung zu starten. Der request kommt dann richtig an.
