### ISSUE TITLE
Formattierung/Text in Tipps & Tricks

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#367]
1) Stellensuche: bitte Zeilenumbrüche zwischen den einzelnen Punkte, man kann es so nicht gut lesen
2) Stellensuche - Unterpunkt Stellensuche - AMS Lehrstellenbörse: Text bitte nicht zentriert sondern linksbündig
3) FAQ - Wer sind wir - Wer hat die App gemacht: statt HAK Friesgasse sollte stehen: HAK AUL Flora Fries

**Comment by leoluttenberger** [comment]
Punkt 1 + 2: hängt vom Bildschirmgröße ab. 
Punkt 3 Ausgebessert
