### ISSUE TITLE
Erinnerungen - Anzeige Termine nicht korrekt

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#371]
Erinnerungen

Eine Bewerbung mit Start 22.6.2023 und Ende 30.9. scheint korrekt bei jedem Tag mit Punkt auf.
In den Termindetails unten scheint es jedoch nur bei Klick auf Tagen nach dem 22. auf (in allen Monaten).
Also: Bei Klick auf 1., 2.,... bis 21. Juli scheint der Termin nicht unten auf (Bild 1)
Bei Klick auf 22.,23.,...31.Juli scheint er unten auf (Bild 2)

Das ist auch bei den anderen Monaten so! (August, September, Anzeige unten immer erst bei Klick auf 22. des Monats oder späteren Tag)

**Expected behavior**
Der Termin sollte an allen Tagen in den Termindetails unten aufscheinen, an denen er läuft bzw. auch ein Punkt in der Übersicht angezeigt wird.

OS: Android 13
![erinnerungen01](https://github.com/leoluttenberger/wedesign/assets/35298425/06bb3a8d-dd6f-4019-bbad-d2541cee6171)
![erinnerungen02](https://github.com/leoluttenberger/wedesign/assets/35298425/0f71c933-035b-4102-8586-04c7697044ea)

**Comment by leoluttenberger** [comment]
fixed in commit bbc011c74bf975ec9ed1a92afee649539e748bc5
