### ISSUE TITLE
Erinnerungen - es werden keine Termine unten angezeigt

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#383]
In der neuesten Version werden bei mir unten keine Termine angezeigt weder wenn ich auf den Termin noch wenn ich auf "Alle Termine im Monat"  klicke

![WhatsApp Image 2023-08-30 at 13 49 07](https://github.com/leoluttenberger/wedesign/assets/122562604/a04f93f3-192a-4941-aa1a-1b79ce4092eb)

**Comment by b-goebl** [comment]
Bei mir werden Termine angezeigt, die in Bewerbungen angelegt sind.
In "Erinnerungen" angelegte Termine nicht. (im Kalender die Punkte sind aber da), also z.B. "Bewerbungsgespräch", "Feedback",...

Falls zeitlich möglich bitte gerne Auswahl lassen nach Tag/Monat umschalten mit dem Button.
Falls, wie als mögliche Zeitspar-Option besprochen, unten alle Termine angezeigt werden und nicht nach Tagen sortiert werden kann, bitte auch bedenken:
1) Der Button muss dann weg
2) Bitte unten die Anzeige zumindest nach Monat filtern, sonst ist es komplett überfüllt! Also im August nur Termine mit Start oder Ende im August z.B.
3) Bitte die Termine unten auch nach Datum sortieren, aktuell ist es irgendeine Reihenfolge und auch veraltete Termin werden angezeigt (s. Punkt 2)
