### ISSUE TITLE
iOS -Dokumente werden auf sozialen Medien nur als Text (Dokumentenname) geteilt, nicht als Datei

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#386]
iOS - Lebenslauf und Bewerbung -> Vorschau & Teilen -> Teilen Icon (beide Formate) -> per EMail verschickt kommt es als Datei an, in Whatsapp kommt es nur als Text an (Dokumentenname "Lebenslauf.pdf")

**Comment by leoluttenberger** [comment]
Fixed in commit 85a3310ba6f0c7f3f66c1607086ae6a978a571da
