### ISSUE TITLE
Alle Versionen (Android, iOS) Drop-Down Menu wird nicht mehr richtig angezeigt 

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#392]
Alle drop-down menu punkte werden abgeschnitten, getestet auf Android, iPhone, Ipad 
![WhatsApp Image 2023-09-13 at 23 34 33](https://github.com/leoluttenberger/wedesign/assets/122562604/e2f47352-4f2e-458c-abec-efd9d9cb5cf8)
![WhatsApp Image 2023-09-13 at 23 35 27](https://github.com/leoluttenberger/wedesign/assets/122562604/80dd8862-6932-43e7-aa4c-6c5af1f54ebb)

**Comment by leoluttenberger** [comment]
Ja wurde alle Text font wurden auf base gesetzt um die native Zoom funktion von iOS in Formularen zu verhindern. 

Dropdowns müssen noch speziell angepasst werden.
