### ISSUE TITLE
Android - Lebenslauf & Bewerbung - Teilen Icon ersetzt, Teilen funktioniert nicht mehr 

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#396]
Android 
Lebenslauf - Vorschau und Teilen - Das alte Teilen Icon ist weg und jetzt sind die zwei Icons von IOS da + Teilen funktioniert nicht mehr (nach der Animation passiert nichts und die Docs werden nicht gespeichert)

Das Gleiche bei Bewerbung -> Motivationsschreiben - Vorschau und Teilen

![WhatsApp Image 2023-09-14 at 00 15 40](https://github.com/leoluttenberger/wedesign/assets/122562604/a0c1651e-077c-4ade-a6fb-60031e0312d5)

**Comment by leoluttenberger** [comment]
Icons wurden wie besprochen geändert für Android und iOS.

Kannst die Apply , dein Gerät verison posten. Danke
