### ISSUE TITLE
Motivationsschreiben: add "aktuelle Version" & "alternative Version"

### ISSUE THREAD

**Issue by vienasus** [leoluttenberger/wedesign#86]

**Comment by leoluttenberger** [comment]
Fixed bug in commit 92509f43208fad571979842882d466a3578d5a9 in main branch.

Added that 5 alternative version on mv are saved and show to the user in edit mv form mode. If there are more than 5 job application only 5 of the current alternative versions  mv are show in edit mv form mode. Current version of mv is visible at the first card.
