### ISSUE TITLE
Sprachkenntnisse Dropdown

### ISSUE THREAD

**Issue by b-goebl** [leoluttenberger/wedesign#91]
Lebenslauf - Kenntnisse - Erfahrung hinzufügen:

Bitte ändern auf "Kenntnisse hinzufügen".

Falls man Typ "Sprachkenntnisse" wählt bitte das Label beim zweiten Dropdown anpassen:
statt Typ --> "Level"

**Comment by leoluttenberger** [comment]
Fixed in commit  d65e530d4c291497bc739f829e1ea76ec64676a9
